
import {setupWorker, rest} from 'msw';
export const tracks = [
  {
    kind: 'track',
    id: 170087114,
    created_at: '2014/09/30 21:53:48 +0000',
    user_id: 77692493,
    duration: 273057,
    commentable: true,
    comment_count: 504,
    state: 'finished',
    original_content_size: 10920128,
    last_modified: '2020/06/22 19:24:08 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'do-i-wanna-know-arctic-monkeys',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Rock',
    title: 'Do I Wanna Know? - Arctic Monkeys',
    description:
      'Do I Wanna Know? - Arctic Monkeys - cover version by Teenage Kicks, wedding and party band.\n\nFor bookings and more info please visit: www.teenagekicksband.co.uk',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/170087114',
    user: {
      id: 77692493,
      kind: 'user',
      permalink: 'teenage-kicks-1',
      username: 'Teenage Kicks.',
      last_modified: '2015/01/16 09:36:26 +0000',
      uri: 'https://api.soundcloud.com/users/77692493',
      permalink_url: 'http://soundcloud.com/teenage-kicks-1',
      avatar_url: 'https://i1.sndcdn.com/avatars-000068249741-0s087d-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/77692493',
    permalink_url:
      'https://soundcloud.com/teenage-kicks-1/do-i-wanna-know-arctic-monkeys',
    artwork_url: null,
    stream_url: 'https://api.soundcloud.com/tracks/170087114/stream',
    download_url: 'https://api.soundcloud.com/tracks/170087114/download',
    waveform_url: 'https://wave.sndcdn.com/vtxazgQAoDxo_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 6456611,
    download_count: 0,
    favoritings_count: 99116,
    reposts_count: 3778,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 114054307,
    created_at: '2013/10/06 08:38:04 +0000',
    user_id: 9324937,
    duration: 154607,
    commentable: true,
    comment_count: 239,
    state: 'finished',
    original_content_size: 3713693,
    last_modified: '2020/06/28 21:39:49 +0000',
    sharing: 'public',
    tag_list: 'AM Cover',
    permalink: 'i-wanna-be-yours-arctic',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'arctic monkeys',
    title: 'I Wanna Be Yours (Arctic Monkeys) Cover',
    description: 'I do not own this song.',
    label_name: '',
    release: '',
    track_type: '',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/114054307',
    user: {
      id: 9324937,
      kind: 'user',
      permalink: 'vincentmcgee',
      username: 'Vincent McGee',
      last_modified: '2020/06/28 21:41:24 +0000',
      uri: 'https://api.soundcloud.com/users/9324937',
      permalink_url: 'http://soundcloud.com/vincentmcgee',
      avatar_url:
        'https://i1.sndcdn.com/avatars-Z3sEWgOZysJtGGKv-wzidyQ-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/9324937',
    permalink_url:
      'https://soundcloud.com/vincentmcgee/i-wanna-be-yours-arctic',
    artwork_url: 'https://i1.sndcdn.com/artworks-000059445013-xkeu19-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/114054307/stream',
    download_url: 'https://api.soundcloud.com/tracks/114054307/download',
    waveform_url: 'https://wave.sndcdn.com/uw8o5iydkMyS_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 4687500,
    download_count: 100,
    favoritings_count: 52539,
    reposts_count: 7020,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 43401524,
    created_at: '2012/04/17 06:20:09 +0000',
    user_id: 8107715,
    duration: 198135,
    commentable: true,
    comment_count: 129,
    state: 'finished',
    original_content_size: 4787986,
    last_modified: '2019/05/26 02:07:10 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'arctic-monkeys-ru-mine-live-on',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: '',
    title: 'Arctic Monkeys R U Mine ?',
    description: '',
    label_name: '',
    release: '',
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'cc-by',
    uri: 'https://api.soundcloud.com/tracks/43401524',
    user: {
      id: 8107715,
      kind: 'user',
      permalink: 'radioriot',
      username: 'RadioRiot',
      last_modified: '2012/04/17 06:15:21 +0000',
      uri: 'https://api.soundcloud.com/users/8107715',
      permalink_url: 'http://soundcloud.com/radioriot',
      avatar_url: 'https://i1.sndcdn.com/avatars-000013612922-plu8qi-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/8107715',
    permalink_url:
      'https://soundcloud.com/radioriot/arctic-monkeys-ru-mine-live-on',
    artwork_url: null,
    stream_url: 'https://api.soundcloud.com/tracks/43401524/stream',
    download_url: 'https://api.soundcloud.com/tracks/43401524/download',
    waveform_url: 'https://wave.sndcdn.com/fsBbdP6qYCLY_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 3691067,
    download_count: 0,
    favoritings_count: 39727,
    reposts_count: 3475,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 148666958,
    created_at: '2014/05/09 11:31:54 +0000',
    user_id: 6524573,
    duration: 163620,
    commentable: true,
    comment_count: 386,
    state: 'finished',
    original_content_size: 6542779,
    last_modified: '2020/06/29 08:29:12 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'arctic-monkeys-feels-like-we-only-go-backwards-tame-impala',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Rock',
    title: 'Arctic Monkeys - Feels Like We Only Go Backwards (Tame Impala)',
    description:
      'Live on Triple J \r\nwww.arcticmonkeysfrance.com\r\nwww.facebook.com/arcticmonkeysfrance',
    label_name: '',
    release: '',
    track_type: '',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/148666958',
    user: {
      id: 6524573,
      kind: 'user',
      permalink: 'arcticmonkeysfrance',
      username: 'arcticmonkeysfrance',
      last_modified: '2018/08/08 21:47:39 +0000',
      uri: 'https://api.soundcloud.com/users/6524573',
      permalink_url: 'http://soundcloud.com/arcticmonkeysfrance',
      avatar_url: 'https://i1.sndcdn.com/avatars-000005272878-q14c48-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/6524573',
    permalink_url:
      'https://soundcloud.com/arcticmonkeysfrance/arctic-monkeys-feels-like-we-only-go-backwards-tame-impala',
    artwork_url: 'https://i1.sndcdn.com/artworks-000078915035-lyoe7f-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/148666958/stream',
    download_url: 'https://api.soundcloud.com/tracks/148666958/download',
    waveform_url: 'https://wave.sndcdn.com/auaXxVf2rbt4_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 3832119,
    download_count: 100,
    favoritings_count: 61291,
    reposts_count: 6403,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 246156095,
    created_at: '2016/02/09 05:38:17 +0000',
    user_id: 170583384,
    duration: 260569,
    commentable: true,
    comment_count: 257,
    state: 'finished',
    original_content_size: 45949456,
    last_modified: '2020/06/03 09:24:23 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'arctic-monkeys-do-i-wanna-knowmp3freex',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Alternative rock',
    title: 'Arctic Monkeys- Do I Wanna Know?',
    description: '',
    label_name: null,
    release: null,
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'wav',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/246156095',
    user: {
      id: 170583384,
      kind: 'user',
      permalink: 'user-502055396',
      username: 'Daz',
      last_modified: '2016/02/07 00:25:37 +0000',
      uri: 'https://api.soundcloud.com/users/170583384',
      permalink_url: 'http://soundcloud.com/user-502055396',
      avatar_url: 'https://i1.sndcdn.com/avatars-000181631166-2670v2-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/170583384',
    permalink_url:
      'https://soundcloud.com/user-502055396/arctic-monkeys-do-i-wanna-knowmp3freex',
    artwork_url: null,
    stream_url: 'https://api.soundcloud.com/tracks/246156095/stream',
    download_url: 'https://api.soundcloud.com/tracks/246156095/download',
    waveform_url: 'https://wave.sndcdn.com/pLg1st0SHQE7_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 2979154,
    download_count: 0,
    favoritings_count: 45178,
    reposts_count: 1503,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 166007443,
    created_at: '2014/09/03 05:49:29 +0000',
    user_id: 111759789,
    duration: 166101,
    commentable: true,
    comment_count: 139,
    state: 'finished',
    original_content_size: 2607487,
    last_modified: '2020/02/16 04:58:18 +0000',
    sharing: 'public',
    tag_list: 'soundcloud:source=deej deej deejapp',
    permalink: 'arctic-monkeys-fluorescent',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: null,
    title: 'Arctic Monkeys - Fluorescent Adolescent',
    description: null,
    label_name: null,
    release: null,
    track_type: 'recording',
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'm4a',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/166007443',
    user: {
      id: 111759789,
      kind: 'user',
      permalink: 'articmonkeys-1',
      username: 'ArticMonkeys',
      last_modified: '2014/09/03 05:39:36 +0000',
      uri: 'https://api.soundcloud.com/users/111759789',
      permalink_url: 'http://soundcloud.com/articmonkeys-1',
      avatar_url: 'https://a1.sndcdn.com/images/default_avatar_large.png',
    },
    user_uri: 'https://api.soundcloud.com/users/111759789',
    permalink_url:
      'https://soundcloud.com/articmonkeys-1/arctic-monkeys-fluorescent',
    artwork_url: 'https://i1.sndcdn.com/artworks-000089923476-zi2e1d-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/166007443/stream',
    download_url: 'https://api.soundcloud.com/tracks/166007443/download',
    waveform_url: 'https://wave.sndcdn.com/CMWzT6HpWutx_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 2466357,
    download_count: 100,
    favoritings_count: 36067,
    reposts_count: 2356,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 71947453,
    created_at: '2012/12/20 12:58:33 +0000',
    user_id: 23988245,
    duration: 171613,
    commentable: true,
    comment_count: 109,
    state: 'finished',
    original_content_size: 49406314,
    last_modified: '2020/06/11 07:58:55 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'flourescent-adolescent-arctic',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Covers',
    title: 'Fluorescent Adolescent - Arctic Monkeys',
    description:
      'Watch the music video here:\r\nhttp://youtu.be/bbwV6mBxidU\r\n\r\nFollow us here:\r\nhttps://twitter.com/LoveJoyFunction\r\nhttps://www.facebook.com/LoveJoyBand\r\n\r\nFor bookings and more info please visit www.lovejoyband.co.uk\r\n\r\nRecorded by Mark Roberts at Empora Recordings. ',
    label_name: '',
    release: '',
    track_type: '',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'wav',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/71947453',
    user: {
      id: 23988245,
      kind: 'user',
      permalink: 'lovejoyband',
      username: 'LoveJoy.',
      last_modified: '2015/01/16 09:41:18 +0000',
      uri: 'https://api.soundcloud.com/users/23988245',
      permalink_url: 'http://soundcloud.com/lovejoyband',
      avatar_url: 'https://i1.sndcdn.com/avatars-000049934461-m5hcwy-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/23988245',
    permalink_url:
      'https://soundcloud.com/lovejoyband/flourescent-adolescent-arctic',
    artwork_url: 'https://i1.sndcdn.com/artworks-000085361674-24powt-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/71947453/stream',
    download_url: 'https://api.soundcloud.com/tracks/71947453/download',
    waveform_url: 'https://wave.sndcdn.com/GpaN9wnceBiP_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 3064620,
    download_count: 100,
    favoritings_count: 32122,
    reposts_count: 2769,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 150437073,
    created_at: '2014/05/20 16:49:39 +0000',
    user_id: 58669269,
    duration: 226058,
    commentable: true,
    comment_count: 165,
    state: 'finished',
    original_content_size: 4661656,
    last_modified: '2020/06/17 14:52:37 +0000',
    sharing: 'public',
    tag_list:
      'indie metal R u mine Arctic Monkeys cool art cover Solo guitar colombia "album AM" AM "alex turner" are you',
    permalink: 'r-u-mine-arctic-monkeys',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: 'Rock',
    title: 'R u mine - Arctic Monkeys',
    description: '',
    label_name: '',
    release: '',
    track_type: '',
    key_signature: '',
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/150437073',
    user: {
      id: 58669269,
      kind: 'user',
      permalink: 'daniiacu',
      username: 'Acuña',
      last_modified: '2019/11/15 11:56:12 +0000',
      uri: 'https://api.soundcloud.com/users/58669269',
      permalink_url: 'http://soundcloud.com/daniiacu',
      avatar_url: 'https://i1.sndcdn.com/avatars-000724143955-ysyl65-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/58669269',
    permalink_url: 'https://soundcloud.com/daniiacu/r-u-mine-arctic-monkeys',
    artwork_url: 'https://i1.sndcdn.com/artworks-000079983387-afqaaz-large.jpg',
    stream_url: 'https://api.soundcloud.com/tracks/150437073/stream',
    download_url: 'https://api.soundcloud.com/tracks/150437073/download',
    waveform_url: 'https://wave.sndcdn.com/Ott5OwnPh9Ea_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 2600785,
    download_count: 0,
    favoritings_count: 29097,
    reposts_count: 2375,
    downloadable: false,
    downloads_remaining: null,
  },
  {
    kind: 'track',
    id: 61802513,
    created_at: '2012/10/01 11:38:14 +0000',
    user_id: 25189025,
    duration: 145880,
    commentable: true,
    comment_count: 201,
    state: 'finished',
    original_content_size: 4737993,
    last_modified: '2018/06/28 00:08:47 +0000',
    sharing: 'public',
    tag_list: '',
    permalink: 'arctic-monkeys-dancing-shoes',
    streamable: true,
    embeddable_by: 'all',
    purchase_url: null,
    purchase_title: null,
    label_id: null,
    genre: '',
    title: 'Arctic Monkeys - Dancing Shoes',
    description: '',
    label_name: '',
    release: '',
    track_type: null,
    key_signature: null,
    isrc: null,
    video_url: null,
    bpm: null,
    release_year: null,
    release_month: null,
    release_day: null,
    original_format: 'mp3',
    license: 'all-rights-reserved',
    uri: 'https://api.soundcloud.com/tracks/61802513',
    user: {
      id: 25189025,
      kind: 'user',
      permalink: '1stfranco',
      username: '1stfranco',
      last_modified: '2018/01/13 18:55:17 +0000',
      uri: 'https://api.soundcloud.com/users/25189025',
      permalink_url: 'http://soundcloud.com/1stfranco',
      avatar_url: 'https://i1.sndcdn.com/avatars-000023540505-3ctqs7-large.jpg',
    },
    user_uri: 'https://api.soundcloud.com/users/25189025',
    permalink_url:
      'https://soundcloud.com/1stfranco/arctic-monkeys-dancing-shoes',
    artwork_url: null,
    stream_url: 'https://api.soundcloud.com/tracks/61802513/stream',
    download_url: 'https://api.soundcloud.com/tracks/61802513/download',
    waveform_url: 'https://wave.sndcdn.com/8jSWSuCyTiM2_m.png',
    domain_lockings: null,
    available_country_codes: null,
    label: null,
    secret_token: null,
    secret_uri: null,
    user_favorite: null,
    user_playback_count: null,
    playback_count: 2249809,
    download_count: 0,
    favoritings_count: 20020,
    reposts_count: 2574,
    downloadable: false,
    downloads_remaining: null,
  },
];


const worker = setupWorker(
  rest.get('https://api.soundcloud.com/tracks', (req, res, ctx) => {
    return res(ctx.json(tracks));
  }),
);

//uncomment to mock apis
// worker.start();
